server:
  #访问HTTP端口号
  port: 8181
  servlet:
    context-path: "/concurrent-demo"


########################################################
### 指定日志文件
########################################################
logging:
  config: classpath:log4j2.xml

