server:
  #访问HTTP端口号
  port: 8182
  servlet:
    context-path: "/smart-office"


########################################################
### 指定日志文件
########################################################
logging:
  config: classpath:log4j2.xml
