server:
  #访问HTTP端口号
  port: 8181
  servlet:
    context-path: "/rabbitmq-demo"


########################################################
### 指定日志文件
########################################################
logging:
  config: classpath:log4j2.xml



########################################################
### 配置RabbitMQ
########################################################
spring:
  rabbitmq:
    host: 106.15.187.228
    port: 5672
    username: admin
    password: admin
    publisher-confirm-type: correlated #发布消息成功或失败到交换器后会触发回调方法
    publisher-returns: true #无法路由到队列中的消息回退
